#!/usr/bin/env bash

## Post-install bare server setup

set -e

packages=(git kitty ripgrep fzf xclip gcc make unzip yarn nodejs npm wget tree-sitter-cli fuse curl)
nvim_appimage="https://github.com/neovim/neovim/releases/download/v0.10.2/nvim.appimage"
nvim_sha256sum="970113b5279718126b82adddf3fbed1741db7afabf8a4134635a0d75c9f2c5d8"

function intro_message() {
    cat << 'EOF'
       _____                 __       
      / ____|               / _|      
     | |     ___  _ __ ___ | |_ _   _ 
     | |    / _ \| '_ ` _ \|  _| | | |
     | |___| (_) | | | | | | | | |_| |
      \_____\___/|_| |_| |_|_|  \__, |
                                 __/ |
                                |___/ 
             Let's get comfy. ☕️
             -------------------
EOF
}

function set_aliases() {
    cat << 'EOF' >> ~/.bashrc

    alias l='ls --group-directories-first --time-style="+%d.%m.%Y %H:%M" --color=auto -hFX'
    alias ll='ls -l --group-directories-first --time-style="+%d.%m.%Y %H:%M" --color=auto -F'
    alias la='ls -la --group-directories-first --time-style="+%d.%m.%Y %H:%M" --color=auto -F'
    alias reload='source ~/.bashrc'
    alias bashrc='nvim ~/.bashrc'
    alias dots='cd ~/.config/ && ya'
    alias vim='nvim'

    function ya() {
        local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
        yazi "$@" --cwd-file="$tmp"
        if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
            builtin cd -- "$cwd"
        fi
        rm -f -- "$tmp"
    }

EOF
}

function list_packages() {
    echo "Here are the packages to install:"
    for i in "${!packages[@]}"; do
        printf "%2d) %s\n" $((i + 1)) "${packages[$i]}"
    done
    echo
}

function install_packages() {
    if [[ ${#packages[@]} -eq 0 ]]; then
        echo "No packages to install."
        return
    fi

    echo "Installing the following packages:"
    for pkg in "${packages[@]}"; do
        echo "  - $pkg"
    done

    sudo apt update -y
    sudo apt install "${packages[@]}" -y
    echo "Packages installed successfully!"
}

function select_packages() {
    echo "Choose packages to exclude (enter numbers or ranges, e.g., 1,3,5-7)."
    echo "Type 'all' to skip installation or just press Enter to install all packages."
    read -p "Your choice: " exclusions

    if [[ -z "$exclusions" ]]; then
        echo "Installing all packages!"
        return 0
    elif [[ "$exclusions" == "all" ]]; then
        echo "Skipping package installation."
        packages=()
        return 0
    fi

    exclude_indices=()
    IFS=',' read -ra ranges <<< "$exclusions"
    for range in "${ranges[@]}"; do
        if [[ "$range" =~ ^[0-9]+$ ]]; then
            exclude_indices+=("$((range - 1))")
        elif [[ "$range" =~ ^([0-9]+)-([0-9]+)$ ]]; then
            for i in $(seq "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"); do
                exclude_indices+=("$((i - 1))")
            done
        else
            echo "Invalid input: $range"
        fi
    done

    for i in "${exclude_indices[@]}"; do
        unset 'packages[i]'
    done

    packages=("${packages[@]}")
}

function install_additional_packages() {
    echo "Installing & setting up neovim..."
    
    mkdir -p ~/.config

    wget "$nvim_appimage"
    result=$(sha256sum nvim.appimage | awk '{print $1}')
    if [[ "$result" == "$nvim_sha256sum" ]]; then
        echo "Neovim SHA256sum verified!"
    else
        echo "SHA256sum doesn't match!"
        echo "Exiting the program!"
        exit 1
    fi
    chmod u+x nvim.appimage
    sudo mv nvim.appimage /usr/bin/nvim
    echo "Neovim installed successfully!"
    
    git clone https://github.com/pindjouf/dotfiles.git
    cp -r dotfiles/hyprlandd/nvim ~/.config && sudo rm -rf dotfiles
    echo "Neovim configuration applied successfully!"

    echo "Setting up btop..."
    sudo apt update -y
    sudo apt install -y coreutils sed git build-essential gcc-11 g++-11 lowdown

    git clone https://github.com/aristocratos/btop.git
    cd btop
    make
    sudo make install
    cd ..
    rm -rf btop
    echo "btop installed and set up successfully!"

    echo "Installing yazi..."
    if ! command -v cargo &> /dev/null; then
        echo "Rust not found. Installing..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
        echo "Rust installed successfully!"
    fi

    cargo install --locked yazi-fm yazi-cli
    echo "Yazi installed successfully!"
}

function goodbye_message() {
    cat << 'EOF'

      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ~                               ~
      ~  Don't forget to take a deep  ~
      ~  breath and enjoy the little  ~
      ~  things. Your system is now   ~
      ~  a comfy haven. ☕️            ~
      ~                               ~
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

EOF
}

function main() {
    intro_message
    list_packages
    select_packages
    install_packages
    install_additional_packages
    set_aliases
    goodbye_message
}

main
